import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Anuj',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Raja',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'iPhone 13 Pro Max',
      slug: 'iphone-13-pro-max',
      category: 'Smartphone',
      image: '/images/p5.png',
      price: 2000,
      countInStock: 50,
      brand: 'Apple',
      rating: 4.6,
      numReviews: 100,
      description: 'Premium Smartphone from Apple',
    },
    {
      // _id: '6',
      name: 'Samsung S22 Ultra',
      slug: 'samsung-s22-ultra',
      category: 'Smartphone',
      image: '/images/p6.jpg',
      price: 1900,
      countInStock: 550,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 300,
      description: 'Premium Smartphone from Samsung',
    },
    {
      // _id: '7',
      name: 'OnePlus 11 Pro',
      slug: 'oneplus-11-pro',
      category: 'Smartphone',
      image: '/images/p7.jpg',
      price: 1000,
      countInStock: 230,
      brand: 'OnePlus',
      rating: 4.2,
      numReviews: 210,
      description: 'Premium Smartphone from OnePlus',
    },
    {
      // _id: '8',
      name: 'Nothing Phone (1)',
      slug: 'nothing-phone-1',
      category: 'Smartphone',
      image: '/images/p8.jpeg',
      price: 300,
      countInStock: 150,
      brand: 'Nothing',
      rating: 4.8,
      numReviews: 80,
      description: 'Flagship Killer from Nothing',
    },
    {
      // _id: '9',
      name: 'Apple Watch Series 6',
      slug: 'apple-watch-series-6',
      category: 'Smartwatch',
      image: '/images/p9.jpeg',
      price: 140,
      countInStock: 250,
      brand: 'Apple',
      rating: 3.9,
      numReviews: 180,
      description: 'Smartwath by Apple',
    },
    {
      // _id: '10',
      name: 'Fastrack Watch',
      slug: 'fastrack-watch',
      category: 'Watch',
      image: '/images/p10.jpg',
      price: 80,
      countInStock: 450,
      brand: 'Fastrack',
      rating: 3.8,
      numReviews: 180,
      description: 'Fastrack Watch',
    },
    {
      // _id: '11',
      name: 'Sunglasses',
      slug: 'sunglasess',
      category: 'Sunglasses',
      image: '/images/p11.jpg',
      price: 30,
      countInStock: 180,
      brand: 'Other',
      rating: 3.5,
      numReviews: 110,
      description: 'Sun Glasses',
    },
    {
      // _id: '12',
      name: 'Apple Airpods',
      slug: 'apple-airpods',
      category: 'Wireless-Earbuds',
      image: '/images/p12.jpeg',
      price: 150,
      countInStock: 500,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 800,
      description: 'Apple Airpods',
    },
    {
      // _id: '13',
      name: 'Blutooth Speaker',
      slug: 'blutooth-speaker',
      category: 'Speaker',
      image: '/images/p13.jpeg',
      price: 10,
      countInStock: 350,
      brand: 'Sony',
      rating: 4.0,
      numReviews: 180,
      description: 'Flagship Killer from Sony',
    },
    {
      // _id: '14',
      name: 'Blutooth Neckband',
      slug: 'neckband',
      category: 'Neckband',
      image: '/images/p14.jpg',
      price: 20,
      countInStock: 750,
      brand: 'Sony',
      rating: 3.8,
      numReviews: 830,
      description: 'Flagship Killer Sony',
    },
    {
      // _id: '15',
      name: 'Macbook Pro',
      slug: 'macbook-pro-apple',
      category: 'Laptop',
      image: '/images/p15.jpeg',
      price: 3000,
      countInStock: 1500,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 800,
      description: 'Apple Macbook Pro',
    },
    {
      // _id: '16',
      name: 'Washing Machine',
      slug: 'washing-machine',
      category: 'Washing Machine',
      image: '/images/p16.jpeg',
      price: 200,
      countInStock: 1150,
      brand: 'LG',
      rating: 2.9,
      numReviews: 80,
      description: 'Washing Machine from LG',
    },
  ],
};

export default data;
